version: '3.3'

services:

# APP #

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
#   privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
#     - SUBFOLDER=/ #optional
    volumes:
      - ./data:/config
#     - ./docker.sock:/var/run/docker.sock #optional
    ports:
      - 8200:3000
#    shm_size: "1gb" #optional
    restart: unless-stopped    



    



