version: '3.3'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/root/Share
    ports:
      - 8200:80
    restart: unless-stopped    



    



